[package]
name = "app"
version = "2026.143.436"
description = "Discover the Wisdom of the Buddha - A lean, fast, and beautiful Sutta reader"
authors = ["Vijjo"]
license = "MIT"
repository = "https://github.com/vjjda/random-sutta"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.0", features = [] }
tauri-plugin-log = "2"
tauri-plugin-deep-link = "2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-web-kit = "0.3.2"
