# Path: src/sutta_processor/optimizer/config.py
from pathlib import Path
from ..shared.app_config import (
    DIST_DB_DIR, 
    DEV_MIRROR_DB_DIR, 
    DIST_JS_MODULES_DIR,
    DB_CHUNK_SIZE_BYTES,
    CONFIG_PRIMARY_BOOKS
)

# Output Directories
WEB_DB_DIR = DIST_DB_DIR
MIRROR_DB_DIR = DEV_MIRROR_DB_DIR
JS_OUTPUT_DIR = DIST_JS_MODULES_DIR

# Settings
CHUNK_SIZE_LIMIT = DB_CHUNK_SIZE_BYTES
PRIMARY_BOOKS_SET = set(CONFIG_PRIMARY_BOOKS)
PRIMARY_BOOKS_LIST = CONFIG_PRIMARY_BOOKS