# Path: src/sutta_processor/optimizer/pool_manager.py
import json
import logging
from typing import Dict, Set, List
from .config import JS_OUTPUT_DIR, PRIMARY_BOOKS_LIST, PRIMARY_BOOKS_SET

logger = logging.getLogger("Optimizer.Pools")

IGNORED_IDS = {'tpk', 'sutta', 'vinaya', 'abhidhamma'}

class PoolManager:
    def __init__(self):
        self.book_counts: Dict[str, int] = {}
        self.sutta_universe: Set[str] = set()

    def register_book_count(self, book_id: str, count: int) -> None:
        self.book_counts[book_id] = count

    def set_sutta_universe(self, books: List[str]) -> None:
        self.sutta_universe = set(books)

    def generate_js_constants(self) -> None:
        # Logic: Sách thuộc nhánh Sutta TRỪ Primary TRỪ System IDs
        candidates = self.sutta_universe - PRIMARY_BOOKS_SET - IGNORED_IDS
        
        valid_secondary = []
        for book_id in candidates:
            # Phải là sách đã được processed (có trong book_counts)
            if book_id in self.book_counts:
                valid_secondary.append(book_id)

        sorted_secondary = sorted(valid_secondary)
        
        content = (
            "// Path: web/assets/modules/data/constants.js\n"
            "// Auto-generated by SuttaProcessor\n\n"
            f"export const PRIMARY_BOOKS = {json.dumps(PRIMARY_BOOKS_LIST, indent=2)};\n\n"
            f"export const SECONDARY_BOOKS = {json.dumps(sorted_secondary, indent=2)};\n\n"
            "// Map: { book_id: valid_sutta_count }\n"
            f"export const SUTTA_COUNTS = {json.dumps(self.book_counts, indent=2, sort_keys=True)};\n"
        )

        file_path = JS_OUTPUT_DIR / "data" / "constants.js"
        file_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        logger.info(f"   ✨ Generated constants.js (Secondary: {len(sorted_secondary)} books)")