# Path: src/sutta_processor/optimizer/pool_manager.py
import json
import logging
from typing import Dict, List, Set
from .config import JS_OUTPUT_DIR, PRIMARY_BOOKS_LIST

logger = logging.getLogger("Optimizer.Pools")

class PoolManager:
    def __init__(self):
        # Lưu số lượng bài kinh hợp lệ cho mỗi sách: {"dn": 34, "mn": 152}
        self.book_counts: Dict[str, int] = {}
        
    def register_book_count(self, book_id: str, count: int) -> None:
        """Worker gọi hàm này sau khi xử lý xong 1 cuốn sách."""
        if count > 0:
            self.book_counts[book_id] = count

    def generate_js_constants(self) -> None:
        """
        Sinh file constants.js chứa SUTTA_COUNTS để Frontend dùng cho Weighted Random.
        """
        # 1. Tách Primary và Secondary (Logic hiển thị filter)
        secondary_books = []
        for book_id in self.book_counts.keys():
            if book_id not in PRIMARY_BOOKS_LIST:
                secondary_books.append(book_id)

        sorted_secondary = sorted(secondary_books)
        
        # 2. Nội dung JS
        # SUTTA_COUNTS là trái tim của Weighted Random
        content = (
            "// Path: web/assets/modules/data/constants.js\n"
            "// Auto-generated by SuttaProcessor\n"
            "// Contains weighted counts for random distribution.\n\n"
            
            f"export const PRIMARY_BOOKS = {json.dumps(PRIMARY_BOOKS_LIST, indent=2)};\n\n"
            
            f"export const SECONDARY_BOOKS = {json.dumps(sorted_secondary, indent=2)};\n\n"
            
            "// Map: { book_id: valid_sutta_count }\n"
            f"export const SUTTA_COUNTS = {json.dumps(self.book_counts, indent=2, sort_keys=True)};\n"
        )

        # 3. Ghi file
        file_path = JS_OUTPUT_DIR / "data" / "constants.js"
        file_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        logger.info(f"   ✨ Generated constants.js with Weights (Total Books: {len(self.book_counts)})")