# Path: src/sutta_processor/optimizer/pool_manager.py
import json
import logging
from typing import Dict, List
from .config import JS_OUTPUT_DIR, PRIMARY_BOOKS_LIST, PRIMARY_BOOKS_SET

logger = logging.getLogger("Optimizer.Pools")

# Các ID hệ thống cần loại bỏ khỏi danh sách sách
IGNORED_IDS = {'tpk', 'sutta', 'vinaya', 'abhidhamma'}

class PoolManager:
    def __init__(self):
        self.book_counts: Dict[str, int] = {}

    def register_book_count(self, book_id: str, count: int) -> None:
        # Lưu count >= 0 (kể cả 0 để biết sách đó tồn tại)
        self.book_counts[book_id] = count

    def generate_js_constants(self) -> None:
        """
        Sinh file constants.js.
        Secondary = (All Processed - Primary - Ignored)
        """
        all_processed = set(self.book_counts.keys())
        
        # Logic trừ tập hợp đơn giản, chính xác
        candidates = all_processed - PRIMARY_BOOKS_SET - IGNORED_IDS
        
        # Chỉ lấy sách có count > 0 (tức là có bài để đọc)
        valid_secondary = []
        for book_id in candidates:
            if self.book_counts[book_id] > 0:
                valid_secondary.append(book_id)

        sorted_secondary = sorted(valid_secondary)
        
        content = (
            "// Path: web/assets/modules/data/constants.js\n"
            "// Auto-generated by SuttaProcessor\n\n"
            f"export const PRIMARY_BOOKS = {json.dumps(PRIMARY_BOOKS_LIST, indent=2)};\n\n"
            f"export const SECONDARY_BOOKS = {json.dumps(sorted_secondary, indent=2)};\n\n"
            "// Map: { book_id: valid_sutta_count }\n"
            f"export const SUTTA_COUNTS = {json.dumps(self.book_counts, indent=2, sort_keys=True)};\n"
        )

        file_path = JS_OUTPUT_DIR / "data" / "constants.js"
        file_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        logger.info(f"   ✨ Generated constants.js (Secondary: {len(sorted_secondary)} books)")